# Title Name: Assassin's Creed: Revelations
# Title ID: 55530879

[GPU]
framerate_limit = 120 # Caps the framerate to 60.
occlusion_query = "strict" # Prevent unoccluded lens flares and fixes geometry flickering.